baseurl: ''
permalink: pretty
title: Лечение трихотилломании и помощь при ТТМ
description: "Коновалова Оксана - психотерапевт. Лечение трихотилломании (ТТМ),
дерматилломании, тревожных мыслей, неврозов  и навязчивых состояний"
url: "https://ttm-help.ru"
permalink: /:slug.html

logo:
  mobile: "assets/images/logo/mobile-logo.svg"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  indentWidth: 4
  style: compressed # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-feed

exclude:
  - "*.iml"
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
