baseurl: '/'
permalink: pretty
title: 'Солопова Оксана'

logo:
  mobile: "images/logo/logo-mobile.png"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.png"
  desktop_height: "32px"
  desktop_width: "120px"


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  indentWidth: 4
  style: compressed # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - "*.iml"
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
