baseurl: ''
title: Лечение трихотилломании и помощь при ТТМ
description:
  Коновалова Оксана - психотерапевт. Лечение трихотилломании (ТТМ), дерматилломании, 
  тревожных мыслей, неврозов и навязчивых состояний
url: "https://ttm-help.ru"
permalink: /:slug.html
image: /assets/img/main-page-image.jpg

author:
  image: /assets/images/illustrations/about-photo.jpg
  name: Оксана Коновалова
  about: Когнитивно-поведенческий психотерапевт, основатель проекта TTM-HELP

logo:
  mobile: "assets/images/logo/mobile-logo.svg"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  indentWidth: 4
  precision: 10
  style: compressed # possible values: nested expanded compact compressed
  sourcemap: always

plugins:
  - jekyll-feed
  - jekyll-sass-converter

exclude:
  - "*.iml"
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
